apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1 
  template:
    spec:
      containers:
      - name: aml-ws
        image: amllibrary:23.05.03
        imagePullPolicy: Never
        command: [
          "python",
          "web_service.py"
        ]
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: "/mnt"
          name: vol
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: claim